### ISSUE TITLE
Implement Floorplan

### ISSUE THREAD

**Issue by zanix** [zanix/home-assistant-config#2]
Add Floorplan for Home Assistant
https://community.home-assistant.io/t/floorplan-for-home-assistant/17394

- [ ] Design SVG
 https://github.com/pkozul/ha-floorplan#creating-a-floorplan-svg-file
- [ ] Alert page
 Using rest command, navigate screens to show alert page with weather or other related alerts.
- [ ] Upgrade code
```shell
sudo su -s /bin/bash homeassistant
source /srv/homeassistant/bin/activate
mkdir /srv/homeassistant/src
cd /srv/homeassistant/src
git clone git://github.com/pkozul/ha-floorplan.git
cd /home/homeassistant/.homeassistant
mkdir -p panels
mkdir -p www/custom_ui/floorplan
ln -s /srv/homeassistant/src/ha-floorplan/panels/floorplan.html panels/floorplan.html
ln -s /srv/homeassistant/src/ha-floorplan/www/custom_ui/floorplan/ha-floorplan.html www/custom_ui/floorplan/ha-floorplan.html
```
- [ ] Spinning fan animation
Add spinning fan automation in Floorplan.
```css
@-webkit-keyframes rotation {
  from {
    -webkit-transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(359deg);
  }
}
#fan\.living_room_fan_level,
#fan\.master_bedroom_fan_level {
  transform-origin: center;
}
.fan-on {
  fill: #ff8a65 !important;
  -webkit-animation: rotation 2s infinite linear;
}
.fan-off {
  fill: #424242 !important;
}
```
